---

###
# TABLEAU
###

# Version
tableau_version_major: 2023
tableau_version_minor: 1
tableau_version_patch: 4

# Debian
tableau_deb_package: "tableau-server-{{ tableau_version_major }}-{{ tableau_version_minor }}-{{ tableau_version_patch }}_amd64.deb"
tableau_url_deb: "https://downloads.tableau.com/esdalt/{{ tableau_version_major }}.{{ tableau_version_minor }}.{{ tableau_version_patch }}/{{ tableau_deb_package }}"

# RedHat
tableau_rpm_package: "tableau-server-{{ tableau_version_major }}-{{ tableau_version_minor }}-{{ tableau_version_patch }}_x86_64.rpm"
tableau_url_rpm: "https://downloads.tableau.com/esdalt/{{ tableau_version_major }}.{{ tableau_version_minor }}.{{ tableau_version_patch }}/{{ tableau_rpm_package }}"

tableau_fix_systemd_unit: false

# User
tableau_user: tabadmin
tableau_password: tabadminPwd
tableau_password_encrypted: "$6$26TGUbrC2UhUN7TC$6yxWcTb4tgJuuR4SQpbV7yEVpSSR092.lKp0kqomaB/MgVmjg7SAfnx/lmkNQytSkWUsxNbNdjYxGyvJX5olE."

# Configuration
tableau_data_dir: /opt/tableau/tableau_server
tsm_packages: "/opt/tableau/tableau_server/packages"
tsm_data_dir: /opt/tableau/tsm
tsm_execute_args: "--accepteula"
tsm_licence: ""
tsm_registration:
  zip: 03079
  country: USA
  city: Tablo
  last_name: Smith
  industry: Software
  eula: yes
  title: Software Applications Engineer
  phone: 7786875309
  company: Example
  state: NH
  department: Engineering
  first_name: Jason
  email: tablo@example.com
  company_employees: 1
  opt_in: false
tsm_identity_store_type: local

tsm_deploy_examples: false

tabcmd_admin_username: admin
tabcmd_admin_password: DhnfIZen3dj3d9s2

