---

#########################################################################################
#                                       TABLEAU
#########################################################################################
# Version
tableau_version_major: 2023
tableau_version_minor: 1
tableau_version_patch: 4

# Debian
tableau_deb_package: "tableau-server-{{ tableau_version_major }}-{{ tableau_version_minor }}-{{ tableau_version_patch }}_amd64.deb"
tableau_url_deb: "https://downloads.tableau.com/esdalt/{{ tableau_version_major }}.{{ tableau_version_minor }}.{{ tableau_version_patch }}/{{ tableau_deb_package }}"

# RedHat
#tableau_rpm_package: "tableau-server-{{ tableau_version_major }}-{{ tableau_version_minor }}-{{ tableau_version_patch }}_x86_64.rpm"
#tableau_url_rpm: "https://downloads.tableau.com/esdalt/{{ tableau_version_major }}.{{ tableau_version_minor }}.{{ tableau_version_patch }}/{{ tableau_rpm_package }}"

#########################################################################################
#                                       POSTGRESQL
#########################################################################################
# Version
postgresql_version_major: 42
postgresql_version_minor: 2
postgresql_version_patch: 14

# Packages
postgresql_package: "postgresql-{{ postgresql_version_major }}-{{ postgresql_version_minor }}-{{ postgresql_version_patch }}.jar"

#########################################################################################
#                                       SNOWFLAKE
#########################################################################################
# Version
snowflake_version_major: 2
snowflake_version_minor: 25
snowflake_version_patch: 12

# Packages
snowflake_package: "snowflake-odbc-{{ postgresql_version_major }}-{{ postgresql_version_minor }}-{{ postgresql_version_patch }}.x86_64.deb"

#########################################################################################
#                                       Configuration
#########################################################################################
tableau_data_dir: /opt/tableau/tableau_server
tsm_packages: "/opt/tableau/tableau_server/packages"
tsm_data_dir: /opt/tableau/tsm
tsm_execute_args: "--accepteula --activation-service"
tsm_licence: ""

#########################################################################################
#                                       TSM registration
#########################################################################################
tsm_registration:
  zip: 61115
  country: USA
  city: Machesney Park
  last_name: Experity Health
  industry: Healthcare
  eula: yes
  title: DataOps
  phone: 7786875309
  company: Experity Health
  state: IL
  department: DataOps
  first_name: Experity Health
  email: "DataOps@ExperityHealth.com"
  company_employees: 1
  opt_in: false

# Config Type
tsm_identity_store_type: local
tsm_deploy_examples: false


