---

- name: TABLEAU JDBC Drivers Config | Copy Postgres Package
  copy:
    src: "/opt/pre-install-packages/{{ postgresql_package }}"
    dest: /opt/tableau/tableau_driver/jdbc/
    owner: "{{ ansible_facts['ansible_local']['experity']['tableau']['tableau_user'] }}"
    group: "{{ ansible_facts['ansible_local']['experity']['tableau']['tableau_user'] }}"
    mode: '0644'
  register: copy_postgres_status

- name: TABLEAU JDBC Drivers Config | Install unixodbc
  become: yes
  command: "{{ item }}"
  with_items:
    - apt --fix-broken install
    - apt-get install unixodbc
  ignore_errors: yes

- name: TABLEAU JDBC Drivers Config | Configure Snowflake
  become: yes
  command: "dpkg -i /opt/pre-install-packages/{{ snowflake_package }}"
  register: snowflake_status

- name: TABLEAU JDBC Drivers Config | Apply pending changes
  command: "{{ TSM_EXECUTABLE }}/tsm pending-changes apply"
  vars:
    statuses:
      - "{{ copy_postgres_status is changed }}"
      - "{{ snowflake_status is changed }}"
    changed_statuses: "{{ statuses | reject('==',False) | list }}"
    should_run: "{{ changed_statuses | length > 0 }}"
  when: should_run

- name: TABLEAU Server Initialize | Initialize Tableau Server with TabAdmin
  command: "tabcmd initialuser --server http://localhost --username {{ ansible_facts['ansible_local']['experity']['tableau']['dataopsuser'] }} --password {{ ansible_facts['ansible_local']['experity']['tableau']['dataopsuserpwd'] }}"