---

- name: TABLEAU | Setup Tableau Server
  import_tasks: server-setup.yml
  tags: tableau-server

- name: TABLEAU | Manage Tableau Server Admin account
  become: true
  import_tasks: user.yml
  tags: tableau-user

- name: TABLEAU | Install Tableau Server
  import_tasks: install.yml
  tags: tableau-install

- name: TABLEAU | Configure Tableau Server
  import_tasks: config.yml
  become_user: "{{ ansible_facts['ansible_local']['experity']['tableau']['tableau_user'] }}"
  tags: tableau-config

- name: TABLEAU | Configure Tableau Server SSL
  import_tasks: ssl.yml
  tags: tableau-ssl

- name: TABLEAU | Configure Tableau Server JDBC Drivers
  import_tasks: jdbc-drivers.yml
  tags: tableau-jdbc
