---

- name: TABLEAU USER | Create Tableau Server admin group
  group:
    name: "tsmadmin"
    state: present

- name: Add the user of Dataops-tsmadmin
  user:
    name: dataops-tsmadmin
    password: "{{ ansible_local.experity.tableau.dataopsUserPwd }}"
    comment: "Ansible DataOps User"
    group: tsmadmin
    update_password: on_create
